### ISSUE TITLE
template bug

### ISSUE THREAD

**Issue by cherdantceva** [artifishional/air-m2#84]
I can try this:

`<unit>
    <style type="text/scss">

    </style>
    <div class="selected-lot">

        <unit template key = item>
            <style type="text/scss">
                :scope {
                    font-size: 20px;
                    color: white;
                }
            </style>

            <unit key = body>
                <div class="selected-lot__item">
                   dsfsdfsdf
                </div>
            </unit>

        </unit>

        <unit use = @item ></unit>
        <unit use = @item ></unit>
        <unit use = @item ></unit>
        <unit use = @item ></unit>
        <div class="selected-item">
        </div>

    </div>
</unit>`

and this won't work.
What am i doing wrong or is this a potantional bug?

**Comment by artifishional** [comment]
Scoped style works only in the layer associated with the target object

```
        <unit template key = item>
            <unit key = body>
                <style type="text/scss">
                    :scope {
                        font-size: 20px;
                        color: white;
                    }
                </style>
                <div class="selected-lot__item">
                    dsfsdfsdf
                </div>
            </unit>
        </unit>
```

**Comment by artifishional** [comment]
won't fix
